n1 = int(input('digite primeiro numero: '))
n2 = int(input('difite o segundo numero: '))

print('Soma {} multi'.format(n1 + n2))
print('multiplicação {}'.format(n1 * n2))
print('Divisão {:.2f}'.format(n1 / n2))
print('subtração {}'.format(n1 - n2))
print('Potencia {}'.format(n1 ** n2))
print('Divisão inteira {}'.format(n1 // n2))
print('Resto da Divisão {}'.format(n1 % n2))
